2025-03-29 13:15:45.518 [info] Extension host with pid 9519 started
2025-03-29 13:15:45.518 [info] Skipping acquiring lock for /home/tsrt/.config/VSCodium/User/workspaceStorage/70e5820094e6c9cdf8323b2e0d57990a.
2025-03-29 13:15:45.832 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-03-29 13:15:45.908 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.debugpy
2025-03-29 13:15:46.552 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-03-29 13:15:46.674 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-03-29 13:15:46.733 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-03-29 13:15:46.866 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-03-29 13:15:47.013 [info] Eager extensions activated
2025-03-29 13:15:47.048 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 13:15:47.052 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-03-29 13:20:24.760 [error] [ms-python.python] provider FAILED
2025-03-29 13:20:24.761 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:20:25.223 [error] [ms-python.python] provider FAILED
2025-03-29 13:20:25.223 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:20:25.785 [error] [ms-python.python] provider FAILED
2025-03-29 13:20:25.785 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:20:33.175 [error] [ms-python.python] provider FAILED
2025-03-29 13:20:33.175 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:20:33.675 [error] [ms-python.python] provider FAILED
2025-03-29 13:20:33.675 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:20:44.381 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onTerminalQuickFixRequest:ms-vscode.npm-command'
2025-03-29 13:36:08.464 [error] [ms-python.python] provider FAILED
2025-03-29 13:36:08.464 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:36:09.620 [error] [ms-python.python] provider FAILED
2025-03-29 13:36:09.620 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:39:06.772 [info] ExtensionService#_doActivateExtension vscode.debug-server-ready, startup: false, activationEvent: 'onDebugResolve'
2025-03-29 13:47:28.216 [error] [ms-python.python] provider FAILED
2025-03-29 13:47:28.216 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:47:28.589 [error] [ms-python.python] provider FAILED
2025-03-29 13:47:28.589 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
2025-03-29 13:47:29.590 [error] [ms-python.python] provider FAILED
2025-03-29 13:47:29.590 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
	at ae (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1974693)
	at oe (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1972653)
	at Immediate.<anonymous> (/home/tsrt/.vscode-oss/extensions/ms-python.python-2025.2.0-universal/out/client/extension.js:2:1968947)
	at process.processImmediate (node:internal/timers:483:21)
